name: windows-build-release

on:
  push:
    paths-ignore:
      - 'sql/**'    

concurrency:
  group: ${{ github.head_ref }} || concat(${{ github.ref }}, ${{ github.workflow }})
  cancel-in-progress: true


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  REPO_DIR : ${{github.workspace}}
  BUILD_DIR: ${{github.workspace}}/bin/builddir
  BOOST_TOOLSET: "msvc"
  BOOST_VERSION: "1.87.0"
  
jobs:
  build:
    runs-on: windows-2022
    
    steps:
    #git checkout
    - uses: actions/checkout@v4

    - uses: FranzDiebold/github-env-vars-action@v2.8.0
    - name: Create Build Environment
      run: |
        echo "ARCHIVE_FILENAME=$env:CI_REPOSITORY_NAME-${{matrix.TYPE}}-$env:CI_SHA_SHORT.zip" >> $env:GITHUB_ENV
        cmake -E make_directory ${{ env.BUILD_DIR }}
 
    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.5
      id: install-boost
      with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here: 
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
          boost_version: ${{env.BOOST_VERSION}}
          # OPTIONAL: Specify a platform version
          platform_version: 2022         
          # OPTIONAL: Specify a toolset on windows
          toolset: ${{env.BOOST_TOOLSET}}
          # OPTIONAL: Specify a custon install location
          boost_install_dir: ${{env.BOOST_INSTALL_DIR}}
          # NOTE: If a boost version matching all requirements cannot be found,
          # this build step will fail          
    - name: windows dependencies
      run: |
        #make
        choco install -y make
        #cmake
        choco install -y cmake
        #openssl
        choco install -y openssl --version=3.1.1
      #git bash shell
      shell: bash

    #build and install
    - name: windows build & install
      env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      run: |
        cd $GITHUB_WORKSPACE
        
        mkdir -p build && cd build
        cmake .. -DTOOLS=ON -DELUNA=1 -A x64
        cmake --build . --config RelWithDebInfo --parallel 4
      #git bash shell
      shell: bash
    - name: Check binaries
      run: |
        cd ${{github.workspace}}/build/bin/RelWithDebInfo
        
        dir
          copy "C:/Program Files/MySQL/MySQL Server 8.0/lib/libmysql.dll" ${{github.workspace}}/build/bin/RelWithDebInfo/libmysql.dll
          copy "C:/Program Files/OpenSSL-Win64/bin/libcrypto-3-x64.dll" ${{github.workspace}}/build/bin/RelWithDebInfo/libcrypto-3-x64.dll
          copy "C:/Program Files/OpenSSL-Win64/bin/libssl-3-x64.dll" ${{github.workspace}}/build/bin/RelWithDebInfo/libssl-3-x64.dll
          move ${{github.workspace}}/contrib/lua_scripts ${{github.workspace}}/build/bin/RelWithDebInfo/lua_scripts
        
        ./authserver --version
        ./worldserver --version

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        path: ${{ env.BUILD_DIR }}/build/bin/RelWithDebInfo/
        name: PandariaMasterWin64VS2022
        # Set a custom retention for artifacts
        #retention-days: 7
